ekf_filter_node:
  ros__parameters:
    # … other params …
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: true
    debug_out_file: /home/arash/Documents/debug/file.txt
    permit_corrected_publication: false
    publish_acceleration: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    odom0: /odom
    odom0_config: [true, true, false,
                   false, false, false,
                   true, false, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 2
    odom0_differential: false
    odom0_relative: false
   
